name: Generate CBOM

on:
  workflow_dispatch:

jobs:
  cbom-scan:
    runs-on: ubuntu-latest
    name: CBOM generation
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Build the project using Maven, skipping tests
      - name: Build with Maven
        run: mvn clean package -DskipTests=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Run CBOM scan
      - name: Create CBOM
        uses: PQCA/cbomkit-action@v2.0.0
        id: cbom

      # Upload the CBOM artifact
      - name: Upload CBOM Artifact
        uses: actions/upload-artifact@v4
        with: 
          name: "CBOM"
          path: ${{ steps.cbom.outputs.pattern }}
          if-no-files-found: warn
